/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GlobalNetworkRouteImport } from './routes/global-network'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpecialCargoRouteImport } from './routes/special-cargo'
import { Route as TradeSolutionsRouteImport } from './routes/trade-solutions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as NoticesIndexRouteImport } from './routes/notices.index'
import { Route as NoticesIdRouteImport } from './routes/notices.$id'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkRoute = GlobalNetworkRouteImport.update({
  id: '/global-network',
  path: '/global-network',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialCargoRoute = SpecialCargoRouteImport.update({
  id: '/special-cargo',
  path: '/special-cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeSolutionsRoute = TradeSolutionsRouteImport.update({
  id: '/trade-solutions',
  path: '/trade-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIdRoute = NoticesIdRouteImport.update({
  id: '/notices/$id',
  path: '/notices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-network': typeof GlobalNetworkRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-cargo': typeof SpecialCargoRoute
  '/trade-solutions': typeof TradeSolutionsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/notices/$id': typeof NoticesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-network': typeof GlobalNetworkRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-cargo': typeof SpecialCargoRoute
  '/trade-solutions': typeof TradeSolutionsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/notices/$id': typeof NoticesIdRoute
  '/admin': typeof AdminIndexRoute
  '/notices': typeof NoticesIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/global-network': typeof GlobalNetworkRoute
  '/insights': typeof InsightsRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-cargo': typeof SpecialCargoRoute
  '/trade-solutions': typeof TradeSolutionsRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/notices/$id': typeof NoticesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/global-network'
    | '/insights'
    | '/our-story'
    | '/services'
    | '/sitemap.xml'
    | '/special-cargo'
    | '/trade-solutions'
    | '/admin/new'
    | '/admin/notices'
    | '/insights/$slug'
    | '/notices/$id'
    | '/admin/'
    | '/notices/'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/global-network'
    | '/insights'
    | '/our-story'
    | '/services'
    | '/sitemap.xml'
    | '/special-cargo'
    | '/trade-solutions'
    | '/admin/new'
    | '/admin/notices'
    | '/insights/$slug'
    | '/notices/$id'
    | '/admin'
    | '/notices'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/global-network'
    | '/insights'
    | '/our-story'
    | '/services'
    | '/sitemap.xml'
    | '/special-cargo'
    | '/trade-solutions'
    | '/admin/new'
    | '/admin/notices'
    | '/insights/$slug'
    | '/notices/$id'
    | '/admin/'
    | '/notices/'
    | '/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GlobalNetworkRoute: typeof GlobalNetworkRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialCargoRoute: typeof SpecialCargoRoute
  TradeSolutionsRoute: typeof TradeSolutionsRoute
  NoticesIdRoute: typeof NoticesIdRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network': {
      id: '/global-network'
      path: '/global-network'
      fullPath: '/global-network'
      preLoaderRoute: typeof GlobalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-cargo': {
      id: '/special-cargo'
      path: '/special-cargo'
      fullPath: '/special-cargo'
      preLoaderRoute: typeof SpecialCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-solutions': {
      id: '/trade-solutions'
      path: '/trade-solutions'
      fullPath: '/trade-solutions'
      preLoaderRoute: typeof TradeSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$id': {
      id: '/notices/$id'
      path: '/notices/$id'
      fullPath: '/notices/$id'
      preLoaderRoute: typeof NoticesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GlobalNetworkRoute: GlobalNetworkRoute,
  InsightsRoute: InsightsRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialCargoRoute: SpecialCargoRoute,
  TradeSolutionsRoute: TradeSolutionsRoute,
  NoticesIdRoute: NoticesIdRoute,
  NoticesIndexRoute: NoticesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
